[tool.pylint.'MESSAGES CONTROL']
disable = "no-member,too-many-instance-attributes"
enable = "c-extension-no-member"
good-names = "ax,im,i,j,x,y"

[tool.black]
line-length = 90

[tool.mypy]
install_types = true
ignore_missing_imports = true
allow_redefinition = true
